/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as EventsEventIdSchedulesIndexRouteImport } from './routes/events/$eventId/schedules/index'
import { Route as EventsEventIdSchedulesScheduleIdPreviewRouteImport } from './routes/events/$eventId/schedules/$scheduleId/preview'
import { Route as EventsEventIdSchedulesScheduleIdAttendanceRouteImport } from './routes/events/$eventId/schedules/$scheduleId/attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdSchedulesIndexRoute =
  EventsEventIdSchedulesIndexRouteImport.update({
    id: '/events/$eventId/schedules/',
    path: '/events/$eventId/schedules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdSchedulesScheduleIdPreviewRoute =
  EventsEventIdSchedulesScheduleIdPreviewRouteImport.update({
    id: '/events/$eventId/schedules/$scheduleId/preview',
    path: '/events/$eventId/schedules/$scheduleId/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdSchedulesScheduleIdAttendanceRoute =
  EventsEventIdSchedulesScheduleIdAttendanceRouteImport.update({
    id: '/events/$eventId/schedules/$scheduleId/attendance',
    path: '/events/$eventId/schedules/$scheduleId/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/$eventId/schedules': typeof EventsEventIdSchedulesIndexRoute
  '/events/$eventId/schedules/$scheduleId/attendance': typeof EventsEventIdSchedulesScheduleIdAttendanceRoute
  '/events/$eventId/schedules/$scheduleId/preview': typeof EventsEventIdSchedulesScheduleIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/$eventId/schedules': typeof EventsEventIdSchedulesIndexRoute
  '/events/$eventId/schedules/$scheduleId/attendance': typeof EventsEventIdSchedulesScheduleIdAttendanceRoute
  '/events/$eventId/schedules/$scheduleId/preview': typeof EventsEventIdSchedulesScheduleIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/$eventId/schedules/': typeof EventsEventIdSchedulesIndexRoute
  '/events/$eventId/schedules/$scheduleId/attendance': typeof EventsEventIdSchedulesScheduleIdAttendanceRoute
  '/events/$eventId/schedules/$scheduleId/preview': typeof EventsEventIdSchedulesScheduleIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/tanstack-query'
    | '/events/$eventId/schedules'
    | '/events/$eventId/schedules/$scheduleId/attendance'
    | '/events/$eventId/schedules/$scheduleId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/tanstack-query'
    | '/events/$eventId/schedules'
    | '/events/$eventId/schedules/$scheduleId/attendance'
    | '/events/$eventId/schedules/$scheduleId/preview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/tanstack-query'
    | '/events/$eventId/schedules/'
    | '/events/$eventId/schedules/$scheduleId/attendance'
    | '/events/$eventId/schedules/$scheduleId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  EventsEventIdSchedulesIndexRoute: typeof EventsEventIdSchedulesIndexRoute
  EventsEventIdSchedulesScheduleIdAttendanceRoute: typeof EventsEventIdSchedulesScheduleIdAttendanceRoute
  EventsEventIdSchedulesScheduleIdPreviewRoute: typeof EventsEventIdSchedulesScheduleIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedules/': {
      id: '/events/$eventId/schedules/'
      path: '/events/$eventId/schedules'
      fullPath: '/events/$eventId/schedules'
      preLoaderRoute: typeof EventsEventIdSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedules/$scheduleId/preview': {
      id: '/events/$eventId/schedules/$scheduleId/preview'
      path: '/events/$eventId/schedules/$scheduleId/preview'
      fullPath: '/events/$eventId/schedules/$scheduleId/preview'
      preLoaderRoute: typeof EventsEventIdSchedulesScheduleIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedules/$scheduleId/attendance': {
      id: '/events/$eventId/schedules/$scheduleId/attendance'
      path: '/events/$eventId/schedules/$scheduleId/attendance'
      fullPath: '/events/$eventId/schedules/$scheduleId/attendance'
      preLoaderRoute: typeof EventsEventIdSchedulesScheduleIdAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  EventsEventIdSchedulesIndexRoute: EventsEventIdSchedulesIndexRoute,
  EventsEventIdSchedulesScheduleIdAttendanceRoute:
    EventsEventIdSchedulesScheduleIdAttendanceRoute,
  EventsEventIdSchedulesScheduleIdPreviewRoute:
    EventsEventIdSchedulesScheduleIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
